### ISSUE TITLE
Capture IntelliJ style imports in documentation

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-java#110]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
When writing code in intellij, we like to use similar formatting guidelines for all files. These are included in the intellij-code-style.xml. Nowhere in our setup or conitribution instructions do we list this as a way to follow our style guidelines. 

TODO: add documentation on including style settings in intelliJ to the contributing.md:
https://github.com/Azure/device-telemetry-java/blob/master/CONTRIBUTING.md

**Comment by jillcary** [comment]
This should be done for all Java projects.

**Comment by dluc** [comment]
some repos have the instructions, e.g. see https://github.com/Azure/telemetry-agent-java/blob/master/CONTRIBUTING.md
1. sync the docs across the Java repos
2. sync the code style file
