### ISSUE TITLE
TotalCount - Allow client to request total number of messages, alerts, and rules

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-java#17]
Implement TotalCount endpoint that will return the total count of items for given query parameters.

For example:
/devicetelemetry/v1/alarmcount?from={fromdate}&to={todate}&status={status}&devices={list of IDs}

(May only be needed for alarms)

**Comment by jillcary** [comment]
https://github.com/Azure/device-telemetry-java/pull/97

**Comment by ppathan** [comment]
Done
