### ISSUE TITLE
[Alarms] Rename 'Alerts' to 'Alarms' 

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-java#29]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

Upon review, we have opted to choose the language "alarms" over "alerts" for an issue raised by a rule. This needs to be updated in the existing documentation and APIs

# Expected behavior

Documentation and API uses the terminology "alarms" instead of "alerts"

**Comment by ppathan** [comment]
Done
