### ISSUE TITLE
Add last trigger time property to Rule object

### ISSUE THREAD

**Issue by darrenchuang** [Azure/device-telemetry-java#65]
# Type of issue

- [ ] Bug
- [X] New feature
- [ ] Improvement

# Description

Add last trigger time property to Rule object

# Expected behavior

A time of last trigger. Null if the rule has never been triggered.

**Comment by timlaverty** [comment]
@darrenchuang Can we query the last Alarm triggered for the rule in question to find this instead of adding new api surface?

**Comment by jillcary** [comment]
This information is provided by the Alarm endpoint.
