### ISSUE TITLE
"Rule Deleted" - Alarms for deleted rules cannot access rule details for maintenance page

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-java#75]
# Type of issue

- [x] Bug
- [ ] New feature
- [x] Improvement

# Description

The maintenance displays all open alarms. These alarms are all associated with a rule, and the only information that the alarm has about the rule is the ID (long number that isn't user friendly), and the rule description. To display the rule name and associated info like conditions, the UI needs to query for the RuleID.

Since maintenance page displays all alarms, the alarms that are associated with a deleted rule show as well, but the UI can no longer get the information for that rule since it's been deleted, meaning the UI will need to show "Rule Deleted"

**If we wish to KEEP the Alarms for deleted rules:**
- add rule name & other details to alarm (right now alarms only have the rule ID and description which is never displayed to the user)

**If we wish to DELETE all alarms for deleted rules:**
- delete rule should also delete or close corresponding alarms.

**Comment by jillcary** [comment]
Update:
For now, deleting rules will be disabled so that alarms can never get in this state. 

In the future we will have the delete rule functionality also delete all alarms associated with that rule.

**Comment by timlaverty** [comment]
This:
<<
For now, deleting rules will be disabled so that alarms can never get in this state.

In the future we will have the delete rule functionality also delete all alarms associated with that rule.
>> 
we need for public preview.  Once you've made this fix please move this bug to GA/P1.

**Comment by timlaverty** [comment]
UI delete button removal tracked by: https://github.com/Azure/pcs-remote-monitoring-webui/issues/388

**Comment by ppathan** [comment]
Opened in TFS
