### ISSUE TITLE
GET /messages 200 response with no content

### ISSUE THREAD

**Issue by maple10001** [Azure/device-telemetry-java#90]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

- in 1.0.0-preview build, success response with no content for GET messages

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

- return messages

# Current behavior

- no content

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Java JDK/JRE: ...

# Code to reproduce the bug

```
import org.junit.*;
import org.junit.experimental.categories.Category;

public class MyTest {

    @Test(timeout = 5000)
    public void TestToReproduceIssue() {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by jillcary** [comment]
Update: this is happening for all Java microservices in a java deployment.

**Comment by jillcary** [comment]
This was caused by the Reverse Proxy adding duplicate headers. See https://github.com/Azure/reverse-proxy-dotnet/pull/18
