### ISSUE TITLE
device-telemetry-java  bug

### ISSUE THREAD

**Issue by xzsheng** [Azure/device-telemetry-java#91]
@v-limliu commented on [Wed Oct 11 2017](https://github.com/Azure/pcs-config-java/issues/46)

# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

1. PUT    /v1/rules/:rule_id/  
"DateCreated" is an optional value, should be datetime.now if not providered from request.

2. com.microsoft.azure.iotsolutions.devicetelemetry.services.Rules 
 at line 288.  response.withArray("Items") should be response.withArray("items")

# Steps to reproduce

1.  make a request that without "DateCreated" about   PUT    /v1/rules/:rule_id/   will response  "invalid input" error

2. make a request  about  GET    /v1/rules will response nothing for rules

**Comment by jillcary** [comment]
https://github.com/Azure/device-telemetry-java/pull/92
